//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrTrussardi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compositions
    {
        public int DishId { get; set; }
        public int IngredientId { get; set; }
        public int CId { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Ingredients Ingredients { get; set; }
    }
}
